exozet/docker-php-fpm

- 5.5/Dockerfile
- 5.6/Dockerfile
- 7.0/Dockerfile
- 7.1/Dockerfile
- README.md
I have added the php-soap extension for php 7.0 and 7.1
> added php soap extension

- 5.5/Dockerfile
- 5.6/Dockerfile
- 7.0/Dockerfile
- 7.1/Dockerfile
- 7.2/Dockerfile
- README.md
I have added mysql-client, rsync and sshpass packages #15 #
> added additional software to images

- 5.5/Dockerfile
- 5.6/Dockerfile
- 7.0/Dockerfile
- 7.1/Dockerfile
- 7.2/Dockerfile
- README.md
bzip2 is used for backups in the TCS video management system.
> Adds bzip2

- 5.5/Dockerfile
- 5.6/Dockerfile
- 7.0/Dockerfile
- 7.2/Dockerfile
- README.md
I have only added the imagick extension for php 5.x containers. I don't believe our php 7.x applications use it.
> Add imagick extension

- README.md
Updated readme on how to use your hosts ssh key inside the container
> added "How to use SSH credentials inside container"

- 7.0/Dockerfile
- 7.1/Dockerfile
- 7.2/Dockerfile
- README.md
See https://pecl.php.net/package/Xdebug for more information
> use latest stable xdebug (2.6.1) for >=7.0

- 7.0/Dockerfile
- 7.1/Dockerfile
- 7.2/Dockerfile
- 7.3/Dockerfile
- README.md
and activated it for PHP 7.3
https://pecl.php.net/package-changelog.php?package=memcached&release=3.1.0
> update memcached extension to 3.1.1

- 7.4/Dockerfile
- README.md
Its much faster:
https://twitter.com/Xdebug/status/1204032464924094465
> Upgrade PHP 7.4 Xdebug to 2.9.0

- 7.4/Dockerfile
- 7.4/Dockerfile-alpine
- build_alpine_version.sh
- build_version.sh
- composer.sh
- installs both versions of composer
- upgrades composer 1 to 1.10.17
- installs composer 2 at 2.0.7
- environment variable `COMPOSER_VERSION` decides which version is used, defaults to version 1
> added composer 2 support

- .github/workflows/ci.yml
> Use also -alpine suffix when pushing -alpine images on release/7.4

- README.md
> Add PHP 8.0 to README

- 7.4/Dockerfile
- 7.4/Dockerfile-alpine
- README.md
- composer.sh
> Release/7.4 - added openssh client 

- .github/workflows/ci.yml
Also changed the order of php versions. Newest on first position.
> Added 8.0.2

- .github/workflows/ci.yml
> Fixed variable name for php version

- 7.2/Dockerfile
> php 7.2 - Updated composer1 to 1.10.20 and composer2 to 2.0.11

- 7.1/Dockerfile
> php 7.1 - Updated composer1 to 1.10.20 and composer2 to 2.0.11

- 7.0/Dockerfile
> php 7.0 - Updated composer1 to 1.10.20 and composer2 to 2.0.11

- 5.6/Dockerfile
> php 5.6 - Updated composer1 to 1.10.20 and composer2 to 2.0.11

- 5.5/Dockerfile
> php 5.5 - Updated composer1 to 1.10.20 and composer2 to 2.0.11

- 5.4/Dockerfile
> php 5.4 - Updated composer1 to 1.10.20 and composer2 to 2.0.11

- 7.4/Dockerfile
- 7.4/Dockerfile-alpine
- README.md
> make composer 2 default

- 8.0/Dockerfile
- 8.0/Dockerfile-alpine
added added missing openssh-client
> Feature/8.0 added openssh-client

- 8.1/Dockerfile
- 8.1/Dockerfile-alpine
added added missing openssh-client
> Feature/8.1 added openssh-client

- 8.1/Dockerfile
- 8.1/Dockerfile-alpine
- README.md
upgraded composer1 to 1.10.26
upgraded composer2 to 2.3.5
> release/8.1 composer upgrade regarding CVE-2022-24828

- 8.0/Dockerfile
- 8.0/Dockerfile-alpine
- README.md
upgraded composer1 to 1.10.26
upgraded composer2 to 2.3.5
> Release/8.0 composer upgrade regarding CVE-2022-24828

- .github/workflows/ci.yml
- 8.1/Dockerfile-alpine
alpine imagick upgraded to 3.7.0
> Release/8.1 version upgrades 8.1.4, 8.1.5

- 8.2/Dockerfile
- 8.2/Dockerfile-alpine
- README.md
https://blog.packagist.com/composer-2-7-7/
> Release/8.2 version upgrades - update composer to 2.7.7

- 8.1/Dockerfile
- 8.1/Dockerfile-alpine
- README.md
https://blog.packagist.com/composer-2-7-7/
> Release/8.1 version upgrades - update composer to 2.7.7
